import { ACHIEVEMENTS, ALBUMS, GENOME_UPGRADES, INTERVENTIONS, ORIGIN_ANCHORS, SPECIES, SPECIES_BY_ID, EvolutionGame, ecologyOf, genomeUpgradeCost } from "./game.js";
import { createStage } from "./stage.js";
import { createEvolutionMap } from "./evolution-map.js";

export const SAVE_KEY = "evolution-idle-progression-v2";

const ACHIEVEMENTS_BY_ID = Object.fromEntries(ACHIEVEMENTS.map(item => [item.id, item]));

const RESOURCE_INFO = {
  energy: { name: "Energy &#9889;", text: "The fuel for population growth. Select a living species in the evolution tree, then tap that creature in the world to spend Energy and grow it." },
  adaptation: { name: "Adaptation &#129516;", text: "Generated by living populations. Spend it on survival preparations and ecosystem decisions." },
  memory: { name: "Evolution Memory &#9851;", text: "Earned when a world ends. Unlocks permanent origin checkpoints between worlds." },
  dna: { name: "DNA Fragments &#129516;", text: "Earned at extinction. Spent in the Genome Lab on permanent lineage upgrades." },
  mutation: { name: "Mutation Points &#10022;", text: "Earned at extinction. Reveal a world's hidden condition, or vent extinction pressure." },
  knowledge: { name: "Discovery Knowledge &#128270;", text: "Earned from discoveries and events. Gates late species and rare evolutionary routes." },
  pressure: { name: "Extinction Risk &#9888;", text: "Risk emerges from Ecosystem Health: a balanced, well-fed food web barely climbs, but overgrazing, starvation, and collapsing populations push it up fast. At 100% a catastrophe strikes — face it to bank rewards and carry survivors into the next world." }
};

const ROLE_ICON = {
  producer: "\u{1F33F}", herbivore: "\u{1F407}", omnivore: "\u{1F417}",
  carnivore: "\u{1F98A}", decomposer: "\u{1F344}", post: "\u{1F6F0}\u{FE0F}"
};

const $ = id => document.getElementById(id);

export function startGame({ fast = false, seed = null, fresh = false, admin = false, openCodex = false, openCodexTab = "atlas", openLab = false, settings = {}, audio = null } = {}) {
  const discoveryQueue = [];
  let activeAlbum = "all";
  let saveTimer = null;
  let lastSavedAt = 0;
  let lastExtinctionSummary = null;
  let queuedChoiceEvent = null;
  let hiddenAt = null;
  let tickInterval = null;
  let toastTimer = null;
  let setDrawerOpen = () => {};
  let refreshResourceInfo = () => {};
  let evolutionMap = null;
  let selectedTreeSpeciesId = null;
  const renderCache = {};
  const stage = createStage($("stage-canvas"), {
    getSettings: () => settings,
    onTapCreature: () => {
      const activeId = game.activeLineageId;
      const succeeded = activeId ? game.growPopulation(activeId) : game.generateEnergy();
      if (!succeeded) audio?.denied?.();
      else {
        audio?.[activeId ? "grow" : "click"]?.();
        haptic(activeId ? "medium" : "light");
      }
    }
  });

  if (fresh) localStorage.removeItem(SAVE_KEY);
  const snapshot = loadSnapshot();
  const profileSeed = seed ?? snapshot?.profileSeed ?? randomSeed();

  const game = new EvolutionGame({
    fast,
    seed: profileSeed,
    snapshot,
    onChange: state => {
      render(state);
      scheduleSave();
    },
    onDiscovery: discovery => {
      audio?.discovery?.(discovery.definition.rarity);
      stage.discoveryBurst();
      discoveryQueue.push(discovery);
      showNextDiscovery();
    },
    onChoiceEvent: event => {
      audio?.choice?.();
      queueChoiceEvent(event);
    },
    onExtinctionReady: () => {
      audio?.extinctionWarning?.();
      shake();
      render(game);
    },
    onExtinction: showExtinction,
    onAchievement: achievement => {
      audio?.unlock?.();
      showAchievementToast(achievement);
      renderCache.achievements = "";
    }
  });

  evolutionMap = createEvolutionMap($("evolution-map-canvas"), SPECIES, {
    onSelect: id => {
      selectedTreeSpeciesId = id;
      if (game.runReached.has(id)) {
        game.setActiveSpecies(id);
        renderEvolutionInspector(game);
      }
      else {
        evolutionMap.select(id, { center: true });
        renderEvolutionInspector(game);
      }
    }
  });

  window.prototypeGame = game;
  $("game-shell").hidden = false;
  document.body.classList.add("immersive"); // the fullscreen canvas is the default view

  if (!openLab && snapshot?.savedAt && !game.worldEnded) {
    const elapsed = Math.min(172800, Math.max(0, (Date.now() - snapshot.savedAt) / 1000));
    if (elapsed > 2) game.advanceOffline(elapsed);
  }
  if (!openLab && game.pendingChoice) queueChoiceEvent(game.pendingChoice);

  $("fast-badge").hidden = !fast && !admin;
  $("fast-badge").textContent = admin ? `ADMIN MODE${fast ? " / FAST SIMULATION" : ""}` : "FAST PLAYTEST MODE";
  $("admin-panel").hidden = !admin;

  wireControls();
  wireDialogGuards();
  wireLifecycle();
  wireTabs();
  wireImmersive();
  wireMenu();
  wireResourceInfo();
  if (admin) wireAdminPanel();
  if (!openLab) {
    startLoop();
    stage.start();
    requestAnimationFrame(() => stage.resize());
  }
  render(game);
  if (openCodex) openCodexScreen(openCodexTab);
  if (openLab) openLabScreen();

  return {
    game,
    saveNow,
    onSettingsChanged() {
      startLoop();
      render(game);
    }
  };

  function wireControls() {
    const press = (id, handler, sound = "click") => {
      $(id).addEventListener("click", () => {
        const succeeded = handler();
        if (succeeded === false) audio?.denied?.();
        else audio?.[sound]?.();
      });
    };
    press("create-atom", () => game.createAtom(), "create");
    press("create-molecule", () => game.createMolecule(), "create");
    press("create-organic", () => game.createOrganic(), "create");
    press("create-cell", () => game.createCell(), "create");
    $("evolution-reset").addEventListener("click", () => {
      evolutionMap.resetView();
      audio?.click?.();
    });
    $("evolution-zoom-out").addEventListener("click", () => {
      evolutionMap.zoomBy(0.8);
      audio?.click?.();
    });
    $("evolution-zoom-in").addEventListener("click", () => {
      evolutionMap.zoomBy(1.25);
      audio?.click?.();
    });
    $("stage-evolution").addEventListener("click", () => {
      document.querySelector('[data-tab="evolve"]')?.click();
      setDrawerOpen(true);
      audio?.click?.();
    });
    press("unlock-cellular", () => game.unlockOriginAnchor("cellular"), "unlock");
    press("reveal-hidden", () => {
      const result = game.revealHiddenCondition();
      if (result) renderCache.world = "";
      return result;
    }, "unlock");
    press("vent-pressure", () => game.ventPressure(), "grow");
    // Ecosystem interventions are event-delegated so the dynamically rebuilt
    // population rows (cull / protect) and the static action bar all work.
    $("karma-meter").addEventListener("click", event => {
      const button = event.target.closest("[data-action]");
      if (!button || !button.dataset.action || button.disabled) return;
      const succeeded = runEcoAction(button.dataset.action, button.dataset.target);
      audio?.[succeeded ? "grow" : "denied"]?.();
      if (succeeded) haptic("light");
    });
    $("face-extinction").addEventListener("click", () => {
      if (game.resolveExtinction()) {
        audio?.extinction?.();
        shake();
      }
    });
    $("close-entry").addEventListener("click", () => $("entry-dialog").close());
    $("atlas-search").addEventListener("input", () => renderAtlas(game));
    $("atlas-state-filter").addEventListener("change", () => renderAtlas(game));
    $("fossil-species").addEventListener("change", event => game.setFossilSpecies(event.target.value || null));
    $("close-discovery").addEventListener("click", () => $("discovery-dialog").close());
    $("discovery-dialog").addEventListener("close", () => {
      showNextDiscovery();
      if (!$("discovery-dialog").open && queuedChoiceEvent) showChoiceEvent(queuedChoiceEvent);
    });
    $("begin-next-run").addEventListener("click", () => {
      clearTransientDialogs();
      stage.clearExtinction();
      game.startNextWorld();
      audio?.create?.();
      $("extinction-dialog").close();
    });
  }

  function wireImmersive() {
    // The creature is the catalyze target; Space/Enter is the keyboard equivalent.
    window.addEventListener("keydown", event => {
      if (event.key !== " " && event.key !== "Enter") return;
      const tag = (event.target.tagName || "").toLowerCase();
      if (tag === "input" || tag === "select" || tag === "button" || tag === "textarea") return;
      if (document.querySelector("dialog[open]")) return;
      if ($("panel-drawer").classList.contains("open")) return;
      if (!$("codex-screen").hidden) return;
      const activeId = game.activeLineageId;
      const succeeded = activeId ? game.growPopulation(activeId) : game.generateEnergy();
      if (succeeded) {
        audio?.[activeId ? "grow" : "click"]?.();
        haptic(activeId ? "medium" : "light");
        stage.tap();
      } else audio?.denied?.();
      event.preventDefault();
    });
    // The fullscreen canvas is the default view; the ✕ exits to the main menu.
    $("stage-exit").addEventListener("click", exitToMenu);
  }

  // The panels live in a bottom-sheet drawer so the canvas stays the main view.
  function wireMenu() {
    const drawer = $("panel-drawer");
    const backdrop = $("drawer-backdrop");
    setDrawerOpen = open => {
      if (open) {
        const activeTab = document.querySelector(".tab.active")?.dataset.tab;
        drawer.classList.toggle("evolution-mode", activeTab === "evolve");
      }
      drawer.classList.toggle("open", open);
      backdrop.classList.toggle("show", open);
      if (open) requestAnimationFrame(() => evolutionMap.resize());
    };
    $("stage-menu").addEventListener("click", () => {
      setDrawerOpen(!drawer.classList.contains("open"));
      audio?.click?.();
    });
    $("drawer-close").addEventListener("click", () => { setDrawerOpen(false); audio?.click?.(); });
    backdrop.addEventListener("click", () => setDrawerOpen(false));
    window.addEventListener("keydown", event => {
      if (event.key === "Escape" && drawer.classList.contains("open")) setDrawerOpen(false);
    });
    // The Codex is its own full screen; the only way back to the game is the menu.
    $("stage-codex").addEventListener("click", () => { openCodexScreen(); audio?.click?.(); });
    $("exit-to-menu").addEventListener("click", exitToMenu);
    $("codex-exit").addEventListener("click", exitToMenu);
    $("lab-exit").addEventListener("click", exitToMenu);
  }

  function openCodexScreen(subtab = "atlas") {
    setDrawerOpen(false);
    render(game);
    for (const item of document.querySelectorAll(".codex-subtab")) item.classList.toggle("active", item.dataset.codex === subtab);
    for (const view of document.querySelectorAll(".codex-view")) view.classList.toggle("active", view.dataset.codexView === subtab);
    $("codex-screen").hidden = false;
  }

  function openLabScreen() {
    setDrawerOpen(false);
    render(game);
    $("lab-screen").hidden = false;
  }

  // Exit to the title screen (saving first), skipping the intro on the way back.
  function exitToMenu() {
    saveNow();
    try { sessionStorage.setItem("ei-skip-intro-once", "1"); } catch { /* sessionStorage unavailable */ }
    location.reload();
  }

  // Tap any resource counter (HUD or fullscreen chip) to learn what it does.
  function wireResourceInfo() {
    const info = $("resource-info");
    let openRes = null;
    const close = () => { info.hidden = true; openRes = null; };
    const renderInfo = res => {
      const meta = RESOURCE_INFO[res];
      if (!meta) return;
      const liveValue = res === "pressure"
        ? `<span class="resource-info-value danger-value">Current risk: ${Math.floor(game.pressure)}%</span><span class="resource-info-value karma-value">Ecosystem Health: ${game.ecosystemHealth}%</span>`
        : "";
      info.innerHTML = `<strong>${meta.name}</strong>${liveValue}<p>${meta.text}</p>`;
    };
    refreshResourceInfo = () => {
      if (openRes) renderInfo(openRes);
    };
    document.addEventListener("click", event => {
      const stat = event.target.closest("[data-res]");
      if (stat) {
        const res = stat.dataset.res;
        const meta = RESOURCE_INFO[res];
        if (!meta) return;
        if (openRes === res) { close(); return; }
        openRes = res;
        renderInfo(res);
        info.hidden = false;
        const rect = stat.getBoundingClientRect();
        const width = Math.min(280, window.innerWidth * 0.86);
        const left = Math.max(8, Math.min(rect.left + rect.width / 2 - width / 2, window.innerWidth - width - 8));
        info.style.width = `${width}px`;
        info.style.left = `${left}px`;
        // Prefer below the element, but flip/clamp so it never leaves the screen.
        const height = info.offsetHeight;
        let top = rect.bottom + 8;
        if (top + height > window.innerHeight - 8) top = Math.max(8, window.innerHeight - height - 8);
        info.style.top = `${top}px`;
        event.stopPropagation();
        return;
      }
      if (!event.target.closest("#resource-info")) close();
    });
  }

  // Haptics: real feedback on iOS via the Expo WebView bridge, with a
  // navigator.vibrate fallback for Android browsers.
  function haptic(style = "light") {
    if (!settings.haptics) return;
    try { window.ReactNativeWebView?.postMessage(JSON.stringify({ type: "haptic", style })); } catch { /* not in webview */ }
    if (navigator.vibrate) navigator.vibrate(style === "heavy" ? 40 : style === "medium" ? 22 : 12);
  }

  function wireTabs() {
    const drawer = $("panel-drawer");
    const activateTab = (target, activeTab) => {
      for (const item of document.querySelectorAll(".tab")) item.classList.toggle("active", item === activeTab);
      for (const pane of document.querySelectorAll(".tab-pane")) pane.classList.toggle("active", pane.dataset.pane === target);
      drawer.classList.toggle("evolution-mode", target === "evolve");
      if (target === "evolve") requestAnimationFrame(() => evolutionMap.resize());
    };
    for (const tab of document.querySelectorAll(".tab")) {
      tab.addEventListener("click", () => {
        const target = tab.dataset.tab;
        activateTab(target, tab);
        audio?.click?.();
      });
    }
    const initialTab = document.querySelector(".tab.active");
    if (initialTab) activateTab(initialTab.dataset.tab, initialTab);
    for (const subtab of document.querySelectorAll(".codex-subtab")) {
      subtab.addEventListener("click", () => {
        const target = subtab.dataset.codex;
        for (const item of document.querySelectorAll(".codex-subtab")) item.classList.toggle("active", item === subtab);
        for (const view of document.querySelectorAll(".codex-view")) view.classList.toggle("active", view.dataset.codexView === target);
        audio?.click?.();
      });
    }
  }

  function showAchievementToast(achievement) {
    const toast = $("achievement-toast");
    $("toast-name").textContent = achievement.name;
    $("toast-desc").textContent = achievement.description;
    toast.hidden = false;
    toast.classList.remove("show");
    void toast.offsetWidth;
    toast.classList.add("show");
    if (toastTimer) clearTimeout(toastTimer);
    toastTimer = setTimeout(() => {
      toast.classList.remove("show");
      setTimeout(() => { toast.hidden = true; }, 400);
    }, 3600);
  }

  function wireDialogGuards() {
    // A finished world must not be stranded without restart UI (the decision card
    // can't be dismissed, so its soft-lock is inherent).
    $("extinction-dialog").addEventListener("cancel", event => event.preventDefault());
    $("extinction-dialog").addEventListener("close", () => {
      if (game.worldEnded && lastExtinctionSummary) setTimeout(() => $("extinction-dialog").showModal(), 150);
    });
  }

  function wireLifecycle() {
    if (openLab) {
      window.addEventListener("pagehide", saveNow);
      return;
    }
    document.addEventListener("visibilitychange", () => {
      if (document.hidden) {
        hiddenAt = Date.now();
        saveNow();
      } else if (hiddenAt) {
        const away = (Date.now() - hiddenAt) / 1000;
        hiddenAt = null;
        if (away > 5 && !game.worldEnded) game.advanceOffline(away);
      }
    });
    window.addEventListener("pagehide", saveNow);
  }

  function wireAdminPanel() {
    const grant = (id, apply) => $(id).addEventListener("click", () => {
      apply();
      renderCache.world = "";
      game.changed();
      audio?.click?.();
    });
    grant("admin-energy", () => { game.energy += 1000; });
    grant("admin-adaptation", () => { game.adaptation += 500; });
    grant("admin-memory", () => { game.evolutionMemory += 10; });
    grant("admin-dna", () => { game.dna += 10; });
    grant("admin-mutation", () => { game.mutationPoints += 10; });
    grant("admin-knowledge", () => { game.discoveryKnowledge += 5; });
    grant("admin-pressure", () => { game.pressure = Math.min(100, game.pressure + 25); });
    grant("admin-reveal", () => { game.revealedHiddenModifier = true; });
    $("admin-event").addEventListener("click", () => {
      if (!game.triggerChoiceEvent()) audio?.denied?.();
    });
    $("admin-wipe").addEventListener("click", () => {
      if (confirm("Wipe the local save and reload?")) {
        localStorage.removeItem(SAVE_KEY);
        location.reload();
      }
    });
  }

  function startLoop() {
    if (tickInterval) clearInterval(tickInterval);
    let lastFrame = performance.now();
    tickInterval = setInterval(() => {
      if (document.hidden) {
        lastFrame = performance.now();
        return;
      }
      const now = performance.now();
      const elapsed = Math.min(0.5, (now - lastFrame) / 1000);
      lastFrame = now;
      game.tick(elapsed);
    }, settings.performanceMode ? 500 : 200);
  }

  function shake() {
    if (settings.reducedMotion) return;
    document.body.classList.remove("shake");
    void document.body.offsetWidth;
    document.body.classList.add("shake");
    setTimeout(() => document.body.classList.remove("shake"), 700);
  }

  function render(state) {
    stage.update(state);
    renderStageHud(state);
    $("world-number").textContent = state.worldNumber;
    $("world-seed").textContent = String(state.worldSeed).padStart(8, "0");
    $("world-title").textContent = `${state.dominantBiome.name} World`;
    $("world-age").textContent = formatDuration(state.worldAgeSeconds);
    $("collection-total").textContent = `${state.known.size} / ${SPECIES.length}`;
    $("completion-percent").textContent = `${Math.round(state.known.size / SPECIES.length * 100)}%`;
    $("memory-total").textContent = format(state.evolutionMemory);
    $("dna-total").textContent = format(state.dna);
    $("mutation-total").textContent = format(state.mutationPoints);
    $("knowledge-total").textContent = format(state.discoveryKnowledge);

    const worldKey = `${state.worldNumber}|${state.revealedHiddenModifier}|${Math.floor(state.mutationPoints)}|${state.worldEnded}`;
    if (renderCache.world !== worldKey) {
      renderCache.world = worldKey;
      renderWorld(state);
    }
    renderEcosystem(state);
    renderEconomy(state);
    renderOrigins(state);
    renderEvolutionProgress(state);
    const growKey = [...state.populations].map(([id, pop]) => (state.energy >= 30 + pop * 20 ? 1 : 0)).join("");
    const evolutionKey = `${state.cells}|${state.activeLineageId}|${selectedTreeSpeciesId}|${Math.floor(state.evolutionEnergy)}|${[...state.runReached].join(",")}|${[...state.populations].join(",")}|${SPECIES.map(item => state.speciesStatus(item.id).state).join(",")}|${state.worldEnded}|${growKey}`;
    if (renderCache.evolution !== evolutionKey) {
      renderCache.evolution = evolutionKey;
      renderEvolution(state);
    }
    const eventKey = state.eventLog.map(item => item.id).join("|");
    if (renderCache.events !== eventKey) {
      renderCache.events = eventKey;
      renderEvents(state);
    }
    renderExtinction(state);
    renderMeta(state);
    renderGenome(state);
    const atlasKey = `${activeAlbum}|${[...state.known].join(",")}|${[...state.survivorStamps.keys()].join(",")}|${$("atlas-search").value}|${$("atlas-state-filter").value}|${SPECIES.filter(item => state.speciesStatus(item.id).state === "available").map(item => item.id).join(",")}`;
    if (renderCache.atlas !== atlasKey) {
      renderCache.atlas = atlasKey;
      renderAtlas(state);
    }
    const achKey = [...state.unlockedAchievements].sort().join(",");
    if (renderCache.achievements !== achKey) {
      renderCache.achievements = achKey;
      renderAchievements(state);
    }
    const boardKey = state.leaderboard.map(entry => entry.score).join(",");
    if (renderCache.leaderboard !== boardKey) {
      renderCache.leaderboard = boardKey;
      renderLeaderboard(state);
    }
  }

  function renderStageHud(state) {
    renderStageResources(state);
    renderStageEvolution(state);
    $("stage-biome").textContent = state.currentScene.name;
    const totalPopulation = [...state.populations.values()].reduce((sum, value) => sum + value, 0);
    const ecosystemPill = $("stage-ecosystem");
    ecosystemPill.textContent = `${state.ecosystemHealthState} ${state.ecosystemHealth}% · Pop ${format(totalPopulation)}`;
    ecosystemPill.classList.toggle("strained", state.ecosystemHealth < 60);
    ecosystemPill.classList.toggle("unstable", state.ecosystemHealth < 40);
    const scoreEl = $("stage-score");
    scoreEl.hidden = state.cells < 1;
    scoreEl.textContent = `★ ${format(state.currentScore)}`;
    // Vertical "rising risk" bar — visible once life exists, fills bottom-to-top.
    const pressureBar = $("stage-pressure");
    pressureBar.hidden = !(state.runReached.size > 0 && !state.worldEnded);
    $("stage-pressure-fill").style.height = `${state.pressure}%`;
    pressureBar.classList.toggle("severe", state.pressure >= 90);
    refreshResourceInfo();
    $("stage-action").hidden = !state.awaitingCataclysm || state.worldEnded;
    const hint = $("stage-hint");
    if (state.worldEnded) hint.textContent = "This world has ended.";
    else if (state.awaitingCataclysm) hint.textContent = "The cataclysm is ready.";
    else if (state.activeLineageId) {
      const active = SPECIES_BY_ID[state.activeLineageId];
      hint.textContent = `Tap ${active.name} to grow its population (${format(state.populationGrowthCost(active.id))} Energy)`;
    } else hint.textContent = "Tap your creature to catalyze energy";
    const surviveBadge = $("tab-survive-badge");
    surviveBadge.hidden = !(state.pressure >= 70 && !state.worldEnded);
    const evolveBadge = $("tab-evolve-badge");
    const available = state.evolutionChoices().filter(item => item.state === "available").length;
    evolveBadge.textContent = available > 0 ? String(available) : "";
    evolveBadge.hidden = available === 0;
    // Surface a dot on the canvas menu button when something is worth opening for.
    const menuCrisis = state.pressure >= 70 && !state.worldEnded;
    const menuBadge = $("menu-badge");
    menuBadge.hidden = !(available > 0 || menuCrisis || state.awaitingCataclysm);
    menuBadge.classList.toggle("crisis", menuCrisis || state.awaitingCataclysm);
  }

  function evolutionProgress(state) {
    const choices = state.cells > 0 ? state.evolutionChoices() : [];
    const checkpoint = choices.length ? Math.min(...choices.map(choice => choice.definition.cost)) : 0;
    const ready = choices.some(choice => choice.state === "available");
    const current = checkpoint > 0 ? Math.min(state.evolutionEnergy, checkpoint) : state.evolutionEnergy;
    const percent = checkpoint > 0 ? Math.min(100, state.evolutionEnergy / checkpoint * 100) : 0;
    const remaining = Math.max(0, checkpoint - state.evolutionEnergy);
    const eta = state.evolutionRate > 0 && remaining > 0 ? remaining / state.evolutionRate : 0;
    const next = choices.filter(choice => choice.definition.cost === checkpoint);
    return { choices, checkpoint, ready, current, percent, remaining, eta, next };
  }

  function renderStageEvolution(state) {
    const bar = $("stage-evolution");
    bar.hidden = state.cells < 1 || state.worldEnded;
    if (bar.hidden) return;
    const progress = evolutionProgress(state);
    const lineage = SPECIES_BY_ID[state.activeLineageId]?.name || "Cellular";
    $("stage-evolution-label").textContent = progress.ready ? "Choose your next species" : `${lineage} evolution`;
    $("stage-evolution-value").textContent = progress.checkpoint > 0
      ? `${format(progress.current)} / ${format(progress.checkpoint)} Evolution Energy`
      : "Awaiting a viable route";
    $("stage-evolution-rate").textContent = `+${format(state.evolutionRate)}/sec (${state.evolutionRateMultiplier.toFixed(2)}x lineage)`;
    $("stage-evolution-eta").textContent = progress.ready
      ? `${progress.choices.filter(choice => choice.state === "available").length} choice${progress.choices.filter(choice => choice.state === "available").length === 1 ? "" : "s"} ready`
      : progress.checkpoint > 0
        ? `about ${formatEta(progress.eta)}`
        : "route conditions needed";
    $("stage-evolution-fill").style.width = `${progress.percent}%`;
    bar.classList.toggle("ready", progress.ready);
  }

  // In immersive fullscreen the HUD is hidden, so surface the resources that
  // actually matter (non-zero) as compact icon chips over the stage.
  function renderStageResources(state) {
    const container = $("stage-resources");
    const defs = [
      { key: "energy", icon: "&#9889;", value: state.energy, rate: state.productionRate },
      { key: "adaptation", icon: "&#129516;", value: state.adaptation, rate: state.adaptationRate },
      { key: "memory", icon: "&#9851;", value: state.evolutionMemory },
      { key: "dna", icon: "&#129516;", value: state.dna },
      { key: "mutation", icon: "&#10022;", value: state.mutationPoints },
      { key: "knowledge", icon: "&#128270;", value: state.discoveryKnowledge }
    ];
    const html = defs
      .filter(def => Math.floor(def.value) > 0)
      .map(def => `<span class="stage-res-chip" data-res="${def.key}"><span class="ico">${def.icon}</span><strong>${format(def.value)}</strong>${def.rate ? `<small>+${format(def.rate)}/s</small>` : ""}</span>`)
      .join("");
    if (container.dataset.html !== html) {
      container.dataset.html = html;
      container.innerHTML = html;
    }
  }

  function renderAchievements(state) {
    const grid = $("achievement-grid");
    const progress = state.achievementProgress;
    $("achievement-progress").textContent = `${progress.unlocked} / ${progress.total}`;
    grid.replaceChildren(...ACHIEVEMENTS.map(achievement => {
      const unlocked = state.unlockedAchievements.has(achievement.id);
      const card = document.createElement("article");
      card.className = `achievement-card ${unlocked ? "unlocked" : "locked"}`;
      const hidden = achievement.secret && !unlocked;
      card.innerHTML = `<span class="achievement-mark">${unlocked ? "&#9733;" : achievement.secret ? "?" : "&#9734;"}</span>`
        + `<div><strong>${hidden ? "Secret Achievement" : achievement.name}</strong>`
        + `<small>${hidden ? "Discover this one yourself." : achievement.description}</small></div>`;
      return card;
    }));
  }

  function renderLeaderboard(state) {
    $("best-score").textContent = format(state.bestScore);
    const list = $("leaderboard-list");
    if (state.leaderboard.length === 0) {
      list.innerHTML = '<li class="empty-copy">Survive an extinction to set your first record.</li>';
      return;
    }
    list.replaceChildren(...state.leaderboard.map((entry, index) => {
      const item = document.createElement("li");
      item.className = "leaderboard-row";
      item.innerHTML = `<span class="rank">${index + 1}</span>`
        + `<span class="apex-glyph">${entry.apexGlyph || "?"}</span>`
        + `<div class="board-main"><strong>${format(entry.score)} pts</strong>`
        + `<small>${entry.apex} &middot; ${entry.species} species &middot; World ${entry.world}</small></div>`
        + `<span class="board-cause">${entry.extinction}</span>`;
      return item;
    }));
  }

  function renderWorld(state) {
    $("biome-list").replaceChildren(...state.worldBiomes.map(biome => chip(biome.name, "biome")));
    const modifierChips = state.visibleModifiers.map(modifier => chip(`${modifier.name}: ${modifier.effect}`, "modifier"));
    modifierChips.push(state.revealedHiddenModifier
      ? chip(`Hidden: ${state.hiddenModifier.name} - ${state.hiddenModifier.effect}`, "secret")
      : chip("Hidden condition: ???", "unknown"));
    $("modifier-list").replaceChildren(...modifierChips);
    $("reveal-hidden").hidden = state.revealedHiddenModifier || state.worldEnded;
    $("reveal-hidden").disabled = state.mutationPoints < 1;
  }

  function renderEcosystem(state) {
    const health = state.ecosystemHealth;
    $("karma-value").textContent = `${health}%`;
    $("karma-state").textContent = state.ecosystemHealthState;
    $("karma-fill").style.width = `${health}%`;
    const meter = $("karma-meter");
    meter.classList.toggle("strained", health < 60);
    meter.classList.toggle("unstable", health < 40);
    meter.classList.toggle("critical", health < 20);
    $("karma-copy").textContent = state.runReached.size === 0
      ? "Evolve your first species to seed a living food web."
      : `Extinction risk is moving at ${state.imbalanceRiskMultiplier.toFixed(2)}x from ecosystem balance. Keep producers, herbivores, and predators in proportion.`;

    // One-tap recommended fix for the worst current problem.
    const rec = state.recommendedAction;
    const recEl = $("recommended-action");
    if (rec && !state.worldEnded) {
      recEl.hidden = false;
      recEl.dataset.action = rec.action;
      recEl.dataset.target = rec.target || "";
      recEl.innerHTML = `<span class="rec-label">${rec.label}</span><span class="rec-reason">${rec.reason}</span>`;
    } else {
      recEl.hidden = true;
      recEl.dataset.action = "";
    }

    // The "why" feed: the food web narrates what is happening this moment.
    const causes = state.ecosystemCauses || [];
    $("ecosystem-causes").replaceChildren(...causes.map(item => {
      const row = document.createElement("div");
      const severity = item.severity >= 80 ? "high" : item.severity >= 45 ? "mid" : "low";
      row.className = `eco-cause sev-${severity}`;
      row.textContent = item.text;
      return row;
    }));

    // Live population rows with role, biome, trend, and per-species actions.
    const rows = [...state.populations.entries()].sort((left, right) => right[1] - left[1]);
    const cullReady = state.interventionStatus("cull")?.ready;
    const protectReady = state.interventionStatus("protect")?.ready;
    if (rows.length === 0) {
      const empty = document.createElement("p");
      empty.className = "empty-copy";
      empty.textContent = "No living populations yet.";
      $("karma-populations").replaceChildren(empty);
    } else {
      $("karma-populations").replaceChildren(...rows.map(([id, pop]) => buildPopRow(state, id, pop, cullReady, protectReady)));
    }

    // Refresh the always-present action buttons (cost/cooldown gating).
    for (const key of ["boostPlants", "stabilise"]) {
      const status = state.interventionStatus(key);
      const button = document.querySelector(`#ecosystem-actions [data-action="${key}"]`);
      if (button && status) {
        button.disabled = !status.ready;
        button.classList.toggle("on-cooldown", status.cooldown > 0);
      }
    }
  }

  function buildPopRow(state, id, pop, cullReady, protectReady) {
    const definition = SPECIES_BY_ID[id];
    const eco = ecologyOf(definition) || {};
    const trend = state.popTrend?.get(id) || 0;
    const arrow = trend > 0 ? "▲" : trend < 0 ? "▼" : "–";
    const protectedActive = (state.protectedUntil?.[id] || 0) > state.worldAgeSeconds;
    const fill = Math.min(100, (pop / Math.max(1, eco.cap || 12)) * 100);
    const row = document.createElement("div");
    row.className = `pop-row role-${eco.role || "herbivore"}${id === state.activeLineageId ? " active" : ""}${protectedActive ? " protected" : ""}`;
    row.innerHTML =
      `<span class="pop-role" title="${eco.role || ""}">${ROLE_ICON[eco.role] || "•"}</span>` +
      `<span class="pop-name">${definition?.name || id}</span>` +
      `<span class="pop-biome">${capitalize(eco.biome || definition?.biome || "")}</span>` +
      `<span class="pop-bar"><i style="width:${fill}%"></i></span>` +
      `<span class="pop-count trend-${trend > 0 ? "up" : trend < 0 ? "down" : "flat"}">${arrow} ${pop < 10 ? pop.toFixed(1) : Math.round(pop)}</span>`;
    const actions = document.createElement("span");
    actions.className = "pop-actions";
    const cull = document.createElement("button");
    cull.type = "button"; cull.dataset.action = "cull"; cull.dataset.target = id;
    cull.title = "Cull (40 Adaptation)"; cull.textContent = "✂";
    cull.disabled = !cullReady || pop <= 1;
    const protect = document.createElement("button");
    protect.type = "button"; protect.dataset.action = "protect"; protect.dataset.target = id;
    protect.title = "Protect (60 Adaptation)"; protect.textContent = "\u{1F6E1}";
    protect.disabled = !protectReady || protectedActive;
    actions.append(cull, protect);
    row.append(actions);
    return row;
  }

  function runEcoAction(action, target) {
    switch (action) {
      case "boostPlants": return game.boostPlants(target || mostStressedBiome());
      case "cull": return game.cullSpecies(target);
      case "protect": return game.protectSpecies(target);
      case "introduce": return game.introduceSpecies(target);
      case "stabilise": return game.stabiliseClimate();
      default: return false;
    }
  }

  function mostStressedBiome() {
    let worst = game.dominantBiome?.id;
    let max = -1;
    for (const [id, biome] of game.biomeState) {
      if ((biome.stress || 0) > max) { max = biome.stress || 0; worst = id; }
    }
    return worst;
  }

  function renderEconomy(state) {
    $("energy-value").textContent = format(state.energy);
    $("energy-rate").textContent = `+${format(state.productionRate)}/sec`;
    $("adaptation-value").textContent = format(state.adaptation);
    $("adaptation-rate").textContent = `+${format(state.adaptationRate)}/sec`;
  }

  function renderOrigins(state) {
    const established = state.establishedOrigins;
    $("atoms-value").textContent = established.atoms.toLocaleString();
    $("molecules-value").textContent = established.molecules.toLocaleString();
    $("organics-value").textContent = established.organics.toLocaleString();
    $("cells-value").textContent = established.cells.toLocaleString();
    // The origin chain now assembles itself; the manual buttons are retired.
    for (const id of ["create-atom", "create-molecule", "create-organic", "create-cell"]) $(id).hidden = true;
    const cellular = state.cells > 0;
    $("origin-title").textContent = cellular ? "Cellular Life Established" : "Life Is Assembling";
    $("origin-summary").textContent = cellular
      ? "Every cell retains its atomic, molecular, and organic foundation as origin chemistry continues."
      : "Matter assembles into life automatically — tap your creature to fuel it.";
    $("origin-panel").classList.toggle("completed-panel", cellular);
  }

  function renderEvolutionProgress(state) {
    const progress = evolutionProgress(state);
    $("checkpoint-label").textContent = progress.ready ? "Evolution choice ready" : `Charging at ${format(state.evolutionRate)}/sec`;
    $("checkpoint-value").textContent = progress.checkpoint > 0
      ? `${format(progress.current)} / ${format(progress.checkpoint)} Evolution Energy · ${progress.ready ? "Ready" : formatEta(progress.eta)}`
      : "Route conditions needed before charging can complete";
    $("checkpoint-fill").style.width = `${progress.percent}%`;
    $("evolution-checkpoint").classList.toggle("ready", progress.ready);
  }

  function renderEvolution(state) {
    $("evolution-panel").classList.toggle("locked-panel", state.cells < 1);
    if (evolutionMap) evolutionMap.update(state);
    renderEvolutionInspector(state);
  }

  function renderEvolutionInspector(state) {
    const container = $("species-actions");
    const choices = state.cells > 0 ? state.evolutionChoices() : [];
    if (!selectedTreeSpeciesId) selectedTreeSpeciesId = state.activeLineageId || choices[0]?.definition.id || null;
    const definition = SPECIES_BY_ID[selectedTreeSpeciesId];
    const status = definition ? state.speciesStatus(definition.id) : null;
    const reached = Boolean(definition && state.runReached.has(definition.id));
    const active = reached && state.activeLineageId === definition.id;
    const title = definition?.name || (state.cells > 0 ? "Cellular Life" : "Origins assembling");
    const glyph = definition?.glyph || (state.cells > 0 ? "CE" : "...");
    const group = definition ? `${definition.group} / ${definition.rarity}` : "ORIGIN / CELLULAR";
    const copy = state.cells < 1
      ? "Automatic chemistry is building the first viable cells."
      : definition
        ? definition.fact
        : "The first stable cells are waiting at the root of the tree of life.";
    const statusLabel = active ? "Active species" : reached ? "Living species" : status?.state === "available" ? "Ready to purchase" : status?.state === "revealed" ? "Route revealed" : "Undiscovered route";
    container.innerHTML = `<p class="eyebrow">SELECTED SPECIES</p>`
      + `<div class="evolution-inspector-title"><span class="species-mark">${glyph}</span><div><small>${group}</small><h2>${title}</h2></div></div>`
      + `<p id="evolution-copy" class="muted">${copy}</p>`
      + `<span class="evolution-status ${active || reached ? "reached" : status?.state || "silhouette"}">${statusLabel}</span>`
      + '<div class="evolution-choice-list"></div>';

    const list = container.querySelector(".evolution-choice-list");
    if (state.cells < 1) {
      list.innerHTML = '<p class="evolution-fact">Atoms, molecules, and organics convert automatically as Energy arrives.</p>';
      return;
    }
    if (!definition || !status) {
      list.innerHTML = '<p class="evolution-fact">Select a species node to inspect its population, price, and route.</p>';
      return;
    }

    if (reached) {
      const population = state.populations.get(definition.id) || 1;
      const growthCost = state.populationGrowthCost(definition.id);
      list.innerHTML = `<div class="species-management"><div><span>Population</span><strong>${population}</strong></div><div><span>Growth cost</span><strong>${format(growthCost)} Energy</strong></div></div>`
        + `<p class="evolution-fact">Growing one lineage far beyond the others lowers World Karma and accelerates extinction risk.</p>`;
      const button = document.createElement("button");
      button.type = "button";
      button.className = active ? "primary evolution-action" : "evolution-action";
      if (active) {
        button.innerHTML = `Grow ${definition.name}<span>${format(growthCost)} Energy</span>`;
        button.disabled = state.energy < growthCost || state.worldEnded;
        button.addEventListener("click", () => {
          if (!state.growPopulation(definition.id)) audio?.denied?.();
          else audio?.grow?.();
        });
      } else {
        button.innerHTML = `Become ${definition.name}<span>Population ${population}</span>`;
        button.disabled = state.worldEnded;
        button.addEventListener("click", () => {
          if (!state.setActiveSpecies(definition.id)) audio?.denied?.();
          else audio?.click?.();
        });
      }
      list.append(button);
      return;
    }

    const reasons = status.reasons.filter(reason => !reason.startsWith("Charge "));
    const remaining = Math.max(0, definition.cost - state.evolutionEnergy);
    list.innerHTML = `<div class="species-price"><span>Evolution price</span><strong>${definition.cost} Evolution Energy</strong></div>`
      + (reasons.length ? `<ul class="evolution-requirements">${reasons.slice(0, 4).map(reason => `<li>${reason}</li>`).join("")}</ul>` : `<p class="evolution-fact">${remaining > 0 ? `${format(remaining)} more Evolution Energy · about ${formatEta(remaining / state.evolutionRate)}` : definition.clue}</p>`);
    const buy = document.createElement("button");
    buy.type = "button";
    buy.className = status.state === "available" ? "primary evolution-action" : "evolution-action";
    buy.innerHTML = `Purchase ${definition.name}<span>${definition.cost} Evolution Energy</span>`;
    buy.disabled = status.state !== "available" || state.worldEnded;
    buy.addEventListener("click", () => {
      if (!state.discoverSpecies(definition.id)) audio?.denied?.();
      else audio?.unlock?.();
    });
    list.append(buy);
  }

  function renderEvents(state) {
    $("event-count").textContent = `${state.totalChoiceEvents} choices made`;
    const log = $("event-log");
    if (state.eventLog.length === 0) {
      log.innerHTML = '<p class="empty-copy">Life has not started making questionable decisions yet.</p>';
      return;
    }
    log.replaceChildren(...state.eventLog.slice(0, 8).map(event => {
      const item = document.createElement("article");
      item.className = `event-item ${event.type}`;
      item.innerHTML = `<span>${event.type}</span><p>${event.text}</p>`;
      return item;
    }));
  }

  function renderExtinction(state) {
    $("extinction-panel").classList.toggle("locked-panel", state.runReached.size === 0);
    $("extinction-panel").classList.toggle("crisis", state.pressure >= 90 && !state.worldEnded);
    $("extinction-name").textContent = state.visibleExtinctionName;
    $("pressure-value").textContent = `${Math.floor(state.pressure)}%`;
    $("threat-stage").textContent = state.threatStage;
    $("pressure-fill").style.width = `${state.pressure}%`;
    $("extinction-copy").textContent = extinctionCopy(state);
    $("face-extinction").disabled = !state.awaitingCataclysm || state.worldEnded;
    $("vent-pressure").hidden = state.runReached.size === 0 || state.worldEnded || state.awaitingCataclysm;
    $("vent-pressure").disabled = state.mutationPoints < 2 || state.pressure < 10;

    const preparations = $("preparation-actions");
    const preparationKey = `${state.pressure >= 70}|${state.selectedPreparation}|${state.adaptation >= 50}|${state.worldEnded}|${state.extinction.id}`;
    if (renderCache.preparations === preparationKey) return;
    renderCache.preparations = preparationKey;
    preparations.replaceChildren();
    if (state.pressure >= 70 && !state.worldEnded) {
      for (const preparation of state.extinction.preparation) {
        const button = document.createElement("button");
        button.type = "button";
        button.textContent = preparation;
        button.disabled = Boolean(state.selectedPreparation) || state.adaptation < 50;
        button.classList.toggle("selected", state.selectedPreparation === preparation);
        button.addEventListener("click", () => {
          if (state.selectPreparation(preparation)) audio?.unlock?.();
        });
        preparations.append(button);
      }
    }
  }

  function renderMeta(state) {
    const cellular = ORIGIN_ANCHORS.find(item => item.id === "cellular");
    const unlocked = state.unlockedOrigins.has("cellular");
    $("unlock-cellular").disabled = unlocked || state.evolutionMemory < cellular.memoryCost;
    $("unlock-cellular").textContent = unlocked ? "Cellular Origin Unlocked" : "Unlock Cellular Origin";
    $("origin-checkpoint-copy").textContent = unlocked
      ? `Future worlds may begin at Cell. Next world origin: ${state.activeOrigin === "cellular" ? "Cellular" : "Atomic"}.`
      : `${format(state.evolutionMemory)} / ${cellular.memoryCost} Memory. Extinction rewards unlock the checkpoint.`;
    $("lab-memory-total").textContent = format(state.evolutionMemory);
    $("lab-dna-total").textContent = format(state.dna);
  }

  function renderGenome(state) {
    const genomeKey = `${state.genome.production}|${state.genome.adaptation}|${state.genome.survival}|${Math.floor(state.dna)}`;
    if (renderCache.genome === genomeKey) return;
    renderCache.genome = genomeKey;
    for (const containerId of ["genome-shop", "extinction-genome"]) {
      const container = $(containerId);
      container.replaceChildren();
      for (const [type, upgrade] of Object.entries(GENOME_UPGRADES)) {
        const level = state.genome[type] || 0;
        const maxed = level >= upgrade.maxLevel;
        const cost = genomeUpgradeCost(level);
        const button = document.createElement("button");
        button.type = "button";
        button.className = "genome-button";
        button.disabled = maxed || state.dna < cost;
        button.innerHTML = `<strong>${upgrade.name} <em>Lv ${level}/${upgrade.maxLevel}</em></strong><span>${upgrade.description}</span><small>${maxed ? "Fully sequenced" : `${cost} DNA`}</small>`;
        button.addEventListener("click", () => {
          if (state.buyGenomeUpgrade(type)) audio?.unlock?.();
        });
        container.append(button);
      }
    }
  }

  function renderAtlas(state) {
    renderAtlasTabs(state);
    const progress = state.albumProgress(activeAlbum);
    const album = ALBUMS.find(item => item.id === activeAlbum);
    $("album-progress").textContent = `${progress.known} / ${progress.total}`;
    $("album-description").textContent = album.description;

    const query = $("atlas-search").value.trim().toLowerCase();
    const filter = $("atlas-state-filter").value;
    const entries = progress.members.filter(entry => {
      const atlasState = state.atlasState(entry.id);
      const knownName = state.known.has(entry.id) ? entry.name.toLowerCase() : "";
      if (query && !knownName.includes(query)) return false;
      if (filter === "discovered" && atlasState !== "discovered") return false;
      if (filter === "missing" && atlasState === "discovered") return false;
      if (filter === "reachable" && state.speciesStatus(entry.id).state !== "available") return false;
      if (filter === "survivor" && !state.survivorStamps.has(entry.id)) return false;
      return true;
    });

    const grid = $("encyclopedia-grid");
    grid.replaceChildren();
    for (const entry of entries) {
      const atlasState = state.atlasState(entry.id);
      const button = document.createElement("button");
      button.type = "button";
      button.className = `entry-slot ${atlasState}${state.speciesStatus(entry.id).state === "available" ? " reachable" : ""}`;
      const known = state.known.has(entry.id);
      button.setAttribute("aria-label", known ? entry.name : `Unknown ${entry.group} species`);
      button.innerHTML = `<span class="slot-number">${String(SPECIES.indexOf(entry) + 1).padStart(3, "0")}</span><span class="glyph">${known ? entry.glyph : "?"}</span><span class="slot-name">${known ? entry.name : atlasState === "revealed" ? "Clue available" : "Unknown"}</span>${state.survivorStamps.has(entry.id) ? '<span class="survivor-stamp">S</span>' : ""}`;
      button.addEventListener("click", () => showEntry(entry.id));
      grid.append(button);
    }
  }

  function renderAtlasTabs(state) {
    const tabs = $("atlas-tabs");
    tabs.replaceChildren();
    for (const album of ALBUMS) {
      const progress = state.albumProgress(album.id);
      if (album.id === "survivors" && progress.total === 0) continue;
      const button = document.createElement("button");
      button.type = "button";
      button.classList.toggle("active", activeAlbum === album.id);
      button.innerHTML = `${album.name}<small>${progress.known}/${progress.total}</small>`;
      button.addEventListener("click", () => {
        activeAlbum = album.id;
        renderCache.atlas = "";
        renderAtlas(state);
      });
      tabs.append(button);
    }
  }

  function showNextDiscovery() {
    const dialog = $("discovery-dialog");
    // Don't interrupt the Codex, the boot intro, or the extinction summary.
    if (dialog.open || discoveryQueue.length === 0 || $("extinction-dialog").open) return;
    if (!$("codex-screen").hidden || !$("boot-overlay").hidden) return;
    const discovery = discoveryQueue.shift();
    const isSpecies = discovery.kind === "species";
    $("discovery-kicker").textContent = isSpecies ? "NEW SPECIES DISCOVERED" : "ORIGIN DISCOVERED";
    $("discovery-glyph").textContent = discovery.definition.glyph;
    $("discovery-name").textContent = discovery.definition.name;
    $("discovery-meta").textContent = `${discovery.definition.rarity} / ${discovery.definition.group}`;
    $("discovery-fact").textContent = discovery.definition.fact;
    $("dialog-total").textContent = `${discovery.total} / ${discovery.maximum}`;
    $("new-clue").textContent = isSpecies ? `New clue: ${discovery.nextClue}` : "Origins are tracked separately and do not inflate the Species Atlas.";
    const glyph = $("discovery-glyph");
    glyph.classList.remove("pop");
    void glyph.offsetWidth;
    glyph.classList.add("pop");
    dialog.classList.toggle("mythic", discovery.definition.rarity === "Mythic");
    dialog.showModal();
  }

  function showEntry(id) {
    const definition = SPECIES_BY_ID[id];
    const atlasState = game.atlasState(id);
    const known = game.known.has(id);
    $("entry-number").textContent = `SPECIES ${String(SPECIES.indexOf(definition) + 1).padStart(3, "0")}`;
    $("entry-glyph").textContent = known ? definition.glyph : "?";
    $("entry-name").textContent = known ? definition.name : "Unknown Species";
    $("entry-status").textContent = known ? `${definition.rarity} / ${definition.group}` : atlasState === "revealed" ? "CLUE AVAILABLE" : "UNDISCOVERED";
    $("entry-description").textContent = game.entryClue(id);
    $("entry-albums").replaceChildren(...definition.albums.map(album => chip(ALBUMS.find(item => item.id === album)?.name || album, "album")));
    const status = game.speciesStatus(id);
    $("entry-route").textContent = known
      ? `Known route: ${definition.requires.length ? definition.requires.map(parent => SPECIES_BY_ID[parent].name).join(" + ") : "Cellular life"}. Habitat: ${definition.biome}.`
      : status.reasons.length ? `Current lead: ${status.reasons.join(" / ")}` : definition.clue;
    const stamps = [...(game.survivorStamps.get(id) || [])];
    $("entry-stamps").replaceChildren(...stamps.map(stamp => chip(`${capitalize(stamp)} survivor`, "stamp")));
    $("entry-dialog").showModal();
  }

  // Decisions appear as a bottom-sheet card over the living stage (not a modal),
  // so the creature and the rising risk bar stay visible while you choose.
  function showChoiceEvent(event) {
    if (!event) return;
    // Wait behind any modal summary; it re-shows when that dialog closes.
    if ($("discovery-dialog").open || $("entry-dialog").open || $("extinction-dialog").open) {
      queuedChoiceEvent = event;
      return;
    }
    queuedChoiceEvent = null;
    $("decision-title").textContent = event.title;
    $("decision-copy").textContent = event.text;
    const options = $("decision-options");
    options.replaceChildren();
    for (const option of event.options) {
      const button = document.createElement("button");
      button.type = "button";
      button.innerHTML = `<strong>${option.label}</strong><span>${option.description}</span>`;
      button.addEventListener("click", () => {
        game.resolveChoice(option.id);
        audio?.click?.();
        stage.tap();
        hideDecisionCard();
      });
      options.append(button);
    }
    const card = $("decision-card");
    card.hidden = false;
    document.body.classList.add("deciding");
    requestAnimationFrame(() => card.classList.add("show"));
  }

  function hideDecisionCard() {
    const card = $("decision-card");
    card.classList.remove("show");
    document.body.classList.remove("deciding");
    // Keep it mounted briefly for the slide-out; a still-pending choice keeps it up.
    setTimeout(() => { if (!game.pendingChoice) card.hidden = true; }, 420);
  }

  function queueChoiceEvent(event) {
    queuedChoiceEvent = event;
    showChoiceEvent(event);
  }

  function showExtinction(summary) {
    lastExtinctionSummary = summary;
    clearTransientDialogs();
    stage.playExtinction(summary.extinction.id);
    haptic("heavy");
    $("extinction-dialog-title").textContent = summary.extinction.name;
    $("run-discovery-count").textContent = summary.reached;
    $("new-discovery-count").textContent = summary.newDiscoveries;
    $("survivor-count").textContent = summary.survivors.length;
    $("run-score").textContent = format(summary.score || 0);
    $("reward-list").replaceChildren(
      reward("Evolution Memory", summary.rewards.memory),
      reward("DNA Fragments", summary.rewards.dna),
      reward("Mutation Points", summary.rewards.mutation),
      reward("Discovery Knowledge", summary.rewards.knowledge)
    );

    const fossilSelect = $("fossil-species");
    fossilSelect.replaceChildren(new Option("No fossil selected", ""));
    for (const id of summary.survivors) fossilSelect.add(new Option(SPECIES_BY_ID[id].name, id));
    fossilSelect.value = summary.survivors.includes(game.fossilSpecies) ? game.fossilSpecies : "";
    renderCache.genome = "";
    renderGenome(game);
    renderOriginChoices();
    // Let the catastrophe play on the stage before the fossil-record summary.
    const delay = settings.reducedMotion ? 0 : 1500;
    setTimeout(() => {
      if (game.worldEnded && !$("extinction-dialog").open) $("extinction-dialog").showModal();
    }, delay);
  }

  function renderOriginChoices() {
    const container = $("origin-choice");
    container.replaceChildren();
    for (const anchor of ORIGIN_ANCHORS) {
      const unlocked = game.unlockedOrigins.has(anchor.id);
      const button = document.createElement("button");
      button.type = "button";
      button.disabled = !unlocked;
      button.classList.toggle("selected", game.activeOrigin === anchor.id);
      button.innerHTML = `<strong>${anchor.name}</strong><span>${unlocked ? anchor.description : `Requires ${anchor.memoryCost} Memory`}</span>`;
      button.addEventListener("click", () => {
        game.setActiveOrigin(anchor.id);
        renderOriginChoices();
      });
      container.append(button);
    }
    if (lastExtinctionSummary?.cellularAvailable && !game.unlockedOrigins.has("cellular")) {
      const unlock = document.createElement("button");
      unlock.type = "button";
      unlock.className = "primary";
      unlock.textContent = "Unlock Cellular Origin for 12 Memory";
      unlock.addEventListener("click", () => {
        if (game.unlockOriginAnchor("cellular")) audio?.unlock?.();
        renderOriginChoices();
      });
      container.append(unlock);
    }
  }

  function clearTransientDialogs() {
    discoveryQueue.length = 0;
    queuedChoiceEvent = null;
    for (const id of ["discovery-dialog", "entry-dialog"]) {
      const dialog = $(id);
      if (dialog.open) dialog.close();
    }
    const card = $("decision-card");
    card.classList.remove("show");
    document.body.classList.remove("deciding");
    card.hidden = true;
  }

  function extinctionCopy(state) {
    if (state.runReached.size === 0) return "Biological complexity will eventually destabilize the world.";
    if (state.pressure < 20) return "The ecosystem is stable. This is temporary, but pleasant.";
    if (state.pressure < 45) return "Background instability is rising. The cause remains unclear.";
    if (state.pressure < 70) return state.extinction.omens[Math.min(state.extinction.omens.length - 1, Math.floor((state.pressure - 45) / 9))];
    if (state.pressure < 90) return `${state.extinction.crisis} Spend 50 Adaptation to preserve more lineages.`;
    if (state.pressure < 100) return `${state.extinction.name} is now certain. The world will pause at the final decision.`;
    return "The catastrophe is ready. Choose when to close this fossil record.";
  }

  function scheduleSave() {
    if (saveTimer) return;
    const wait = Math.max(0, 3000 - (Date.now() - lastSavedAt));
    saveTimer = setTimeout(() => {
      saveTimer = null;
      saveNow();
    }, wait);
  }

  function saveNow() {
    if (openLab && !snapshot) return;
    try {
      localStorage.setItem(SAVE_KEY, JSON.stringify(game.exportSnapshot()));
      lastSavedAt = Date.now();
    } catch {
      // The prototype remains playable when storage is unavailable.
    }
  }
}

export function loadSnapshot() {
  try {
    const raw = localStorage.getItem(SAVE_KEY);
    return raw ? JSON.parse(raw) : null;
  } catch {
    return null;
  }
}

function randomSeed() {
  if (crypto?.getRandomValues) {
    const buffer = new Uint32Array(1);
    crypto.getRandomValues(buffer);
    return buffer[0] || 1;
  }
  return (Math.floor(Math.random() * 4294967295) >>> 0) || 1;
}

function chip(text, className) {
  const element = document.createElement("span");
  element.className = `chip ${className}`;
  element.textContent = text;
  return element;
}

function reward(label, amount) {
  const element = document.createElement("div");
  element.innerHTML = `<span>${label}</span><strong>+${amount}</strong>`;
  return element;
}

function format(value) {
  if (value >= 1_000_000) return value.toExponential(2);
  if (value >= 1000) return Math.floor(value).toLocaleString();
  if (value >= 100) return Math.floor(value).toString();
  return value.toFixed(value < 10 ? 1 : 0);
}

function formatDuration(seconds) {
  if (seconds < 60) return `${Math.floor(seconds)}s`;
  if (seconds < 3600) return `${Math.floor(seconds / 60)}m`;
  return `${Math.floor(seconds / 3600)}h ${Math.floor(seconds % 3600 / 60)}m`;
}

function formatEta(seconds) {
  if (!Number.isFinite(seconds) || seconds <= 0) return "ready now";
  if (seconds < 60) return `${Math.max(1, Math.ceil(seconds))}s`;
  if (seconds < 3600) return `${Math.ceil(seconds / 60)}m`;
  return `${Math.floor(seconds / 3600)}h ${Math.ceil(seconds % 3600 / 60)}m`;
}

function capitalize(value) {
  return value.charAt(0).toUpperCase() + value.slice(1).replaceAll("_", " ");
}
